export {default as Loader} from "./Loader"
export {default as Welcome} from "./Welcome"
export {default as Navbar} from "./Navbar"
export {default as Servise} from "./Servise"
export {default as Transection} from "./Transection"
export {default as Footer} from "./Footer"